export { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
export {
  faArrowLeft,
  faArrowRight,
  faBars,
  faCalendarDays,
  faChevronLeft,
  faChevronRight,
  faCircleInfo,
  faClapperboard,
  faClock,
  faEye,
  faEyeSlash,
  faFilter,
  faHouse,
  faLocationDot,
  faMagnifyingGlass,
  faPlay,
  faPlus,
  faStar,
  faTicket,
  faUsers,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

